name: CI

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NPM Auth
        uses: Octav-Labs/github-actions/setup-npm-auth@v1.1.14
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Setup Node
        uses: Octav-Labs/github-actions/setup-node@v1.1.14

      - name: Build
        run: pnpm build
